### ISSUE TITLE
Blender add-on not removing .bdx file for deleted scene

### ISSUE THREAD

**Issue by aliasaila** [GoranM/bdx#573] opened 2016-03-07 05:12 UTC
Just ran a simple test.

1) Create a BDX project.
2) Add a new scene.
3) Export and run.
4) Delete the previously added scene.
5) Export and run.

The .bdx file remains.

I discovered this whilst researching the correct way to remove files for deleted blender objects.

**Comment by SolarLune** [comment] 2016-03-07 15:53
Hey, yeah, this is a bit of a known issue, I guess you could say. 

The problem is that BDX just straight-up doesn't do anything to delete scenes. Not sure if this is a problem that should be solved or not; on the one hand, we could easily delete all exported scenes before export. On the other, this allows people to export scenes (either using the Export menu, or by pressing P to play) from different blend files. Since the option's there in the Export menu, it might be a good idea to not "undermine" that by deleting scenes in the bdx/scenes/ folder. 

Thoughts, @GoranM?

**Comment by GoranM** [comment] 2016-03-07 20:48
> On the other, this allows people to export scenes (either using the Export menu, or by pressing P to play) from different blend files. Since the option's there in the Export menu, it might be a good idea to not "undermine" that by deleting scenes in the bdx/scenes/ folder.

I don't think we should feel under any obligation to support that.

If people want to include a scene from a different .blend, they should include it in blender, so that it becomes a part of the working file.

**Comment by SolarLune** [comment] 2016-03-07 21:50
So we should delete all exported scenes before the scenes in the current blend file are exported?

**Comment by GoranM** [comment] 2016-03-09 03:39
That was the implication, yes.

**Comment by SolarLune** [comment] 2016-05-09 19:48
PR submitted.

**Comment by SolarLune** [comment] 2016-05-12 23:43
Ah, the PR was merged, so this can be closed now.

**Closed** 2016-05-13 20:50 UTC
