### ISSUE TITLE
GameObject scale() and dimensions() not working for empties

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#66] opened 2015-01-18 00:11 UTC
I'm not sure if this is supposed to be or not, but it sure would be nice these attributes worked with empties also.

Sometimes I use an empty for spawning random objects. The scale or dimensions of the empty is an easy reference for the size of the spawning area.

**Comment by GoranM** [comment] 2015-01-18 04:09
Well, technically, not a bug, since this is [something I did knowingly](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/GameObject.java#L295), but it should be made to work in the future, so maybe it's a good idea to treat it as a bug.

The easiest way to make it work is to make every object have a modelInstance, even if they don't have a visual representation (like empties and lights). There's already a defaultModel, so we could just create an instance from that, and set the object to be invisible.

That would also simplify other bits of code.

**Comment by rafcolson** [comment] 2015-01-18 04:33
Wouldn't that add more weight to the number of GL calls? I hope you can fix the performance issue with GL calls on Android. Then that won't be a disadvantage.

**Comment by GoranM** [comment] 2015-01-18 16:55
As far as I know, draw call overhead depends on which objects are [actually rendered](https://github.com/GoranM/bdx/blob/master/blender/bdx/gen/BdxApp.java#L59), not the number of existing model instances, so as long as we set the relevant objects to invisible, I think it should be fine.

For performance in general: I first need to confirm that rendering is the bottleneck. I mean, it's true that rendering is generally slow on mobile platforms, but it's possible that BDX is taking up a significant number of cycles, and that things could be much faster if optimized (in the right places).

Right now, BDX is "touching" all objects, even when not necessary:

The bullet body transform matrix is converted - [for every visible object, on every frame](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L474) - into the proper modelInstance transform matrix. If we were to move that logic into GameObject.transform, we could probably avoid a lot of that overhead, because that conversion would only happen when the object is actually moved.

Objects which don't have code in main, or running components, shouldn't have any additional logic overhead, but that's not quite true, because all of them are still being ["visited" by BDX](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L492), to actually call the main function, and that takes a bit of processing time, even if the function is empty. If we create (and manage) a list of objects that actually need to be processed, instead of iterating through scene.objects (which contains objects that don't), we could probably avoid some overhead.

Whether or not any of those optimizations are worth making depends on how much time it takes to execute BDX logic ( Scene.update() ), relative to how much time it takes to actually render a scene.

This is something that I (or someone else) would need to measure, to confirm things one way or another.

**Comment by rafcolson** [comment] 2015-01-18 20:36
> As far as I know, draw call overhead depends on which objects are actually rendered, not the number of existing model instances, so as long as we set the relevant objects to invisible, I think it should be fine.

Strange, I was pretty sure it didn't make any difference in my project, but I just tested it with 256 cubes, and there is a noticeable difference indeed, when they're visible or not. So again, false alarm. If you want you can check it here(https://www.dropbox.com/sh/99w8b9w40x5mlax/AAAuNdwzWtrtem2hUGiHdtmwa?dl=0).

By the way, the optimization steps you mentioned sound sound like they would make a difference, but we'll never know unless we try it out.

**Comment by GoranM** [comment] 2015-01-19 04:20
We need to time the relevant functions, as I said, or run everything through a profiler of some sort, to confirm that the BDX side is actually worth optimizing.

If libgdx rendering takes more than 80% of the overall time, then optimizing BDX wouldn't make a significant difference, and we would just needlessly complicate the system.

**Comment by rafcolson** [comment] 2015-01-19 04:37
I can't help you with the profiler, I think, but I can do some tests to compare if some optimizations would be worth it. At the moment I'm working on the optimization in scene.detectCollisions(). Until now I don't think it would complicate the system much, but that's for you to decide. So if you want I can share my findings.

**Comment by GoranM** [comment] 2015-01-19 19:49
The easiest test you can run is to actually time the relevant functions, and see how long they take to process, relative to everything else: scene.update() + renderScene().

You should be able to use com.badlogic.gdx.utils.TimeUtils:

```java
long t = TimeUtils.millis();
functionYouWantToTime();
long tt = TimeUtils.millis();
long delta = tt - t;
```

If there is truly a significant performance benefit, I would love to know, of course, but I think it's something we should discuss in a different issue (we're quite off-topic in this one).

**Comment by rafcolson** [comment] 2015-01-22 06:19
@GoranM Should we treat Camera's and Lamps the same way as Empties or should I just give the Empties the defaultModel as a mesh? See [Scene.java](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L170).

**Comment by GoranM** [comment] 2015-01-26 09:48
I'll assume we can close this now.

**Closed by GoranM** 2015-01-26 09:48 UTC
Labels: bug
