### ISSUE TITLE
The blender plugin can't create bdx project

### ISSUE THREAD

**Issue by xirtam-ch** [GoranM/bdx#509] opened 2016-01-21 05:58 UTC
My environment：
Mac OSX 10.10.3
blender 2.7.6
bdx 0.22

I got this error:
File "/Users/xirtam/Library/Application Support/Lbender/2.76/scripts/addons/bdx/ops/createproj.py",line 239 in execute self.set_android_sdk_version()
File "Users/xirtam/Library/Application Support/Blender/2.76/scripts/addons/bdx/ops/createproj.py",line 123 in set_android_sdk_veresion_build_tools_version  = get_version_dir_name(build_tools_dir,build_tools_sort_key,"20.0.0")
File "Users/xirtam/Library/Application Support/Blender/2.76/scripts/addons/bdx/ops/createproj.py",line 105 in get_version_dir_name return sorted(os.listdir(path),key=sort_key)[-1]
File "Users/xirtam/Library/Application Support/Blender/2.76/scripts/addons/bdx/ops/createproj.py",line 114,in build_tools_sort_key h , t ,o = strv.split('.')
ValueError:need more than 2 values to unpack

location:<unkonwn location>:-1

**Comment by xirtam-ch** [comment] 2016-01-21 06:45
I modified the createproj.py to 
build_tools_version = "23.0.2"
compile_sdk_version = "23"
It works now!

**Comment by rafcolson** [comment] 2016-01-21 15:31
I'm curious. Could you maybe look up the exact folder names in the ```android\sdk``` folder? Are the in fact ```23.0.2" and ```23``` and not ```android-23``` by any chance?

**Comment by xirtam-ch** [comment] 2016-01-22 01:55
My folder name is x.x.x and x-x ,yeah, I don't know why too....

**Comment by SolarLune** [comment] 2016-01-22 05:48
"X-X"? What's it actually named?

**Comment by xirtam-ch** [comment] 2016-01-22 05:58
@SolarLune 
android-10	android-14	android-18	android-22	android-8
android-11	android-15	android-19	android-23	android-L
android-12	android-16	android-20	android-4
android-13	android-17	android-21	android-7

Maybe problem is the android-L?

**Comment by raphaelbruno** [comment] 2016-06-29 23:43
I had a similar problem, I got this error:

> Traceback (most recent call last):
>   File "/home/raphael/.config/blender/2.77/scripts/addons/bdx/ops/createproj.py", line 239, in execute
>     self.set_android_sdk_version()
>   File "/home/raphael/.config/blender/2.77/scripts/addons/bdx/ops/createproj.py", line 127, in set_android_sdk_version
>     compile_sdk_version = get_version_dir_name(platforms_dir, compile_sdk_sort_key, "20")
>   File "/home/raphael/.config/blender/2.77/scripts/addons/bdx/ops/createproj.py", line 105, in get_version_dir_name
>     return sorted(os.listdir(path), key=sort_key)[-1]
>   File "/home/raphael/.config/blender/2.77/scripts/addons/bdx/ops/createproj.py", line 118, in compile_sdk_sort_key
>     return int(strv.split('-')[-1])
> ValueError: invalid literal for int() with base 10: 'N'
> 
> location: <unknown location>:-1
> 

My platforms directory is just like this:
_sdk
|_ platforms
   |_ android-22
   |_ android-23
   |_ android-N

I gess the problem is because the name "android-N", it has a letter "N" instead a number, If I remove this directory (android-N), it works. 
I tried to fix using something like that
`            ver = str(strv.split('-')[-1])
            return is_int(ver) ? int(ver) : 0
`
But I'm noob in python :(

So, if someone know how to fix that, I think the problem is on line 118.

**Comment by rafcolson** [comment] 2016-06-30 00:20
>So, if someone know how to fix that, I think the problem is on line 118.

Thanks. However I'm not sure how to handle priority in this case. Should these versions have priority over other versions?

**Comment by rafcolson** [comment] 2016-06-30 00:48
Digits will have priority over non-digits. PR submitted.

**Comment by xirtam-ch** [comment] 2016-06-30 01:31
@rafcolson Never mind :)

**Comment by rafcolson** [comment] 2016-06-30 11:29
@xirtam-ch Thanks. A PR was merged.

**Comment by raphaelbruno** [comment] 2016-06-30 12:22
Oh thanks for the merge, I will test it tonight.

**Comment by rafcolson** [comment] 2016-10-11 02:33
@raphaelbruno

I assume this solved the issue? So could this be closed?

**Comment by SolarLune** [comment] 2017-03-21 22:34
I'm guessing this can be closed, @GoranM.

**Closed** 2017-03-23 04:27 UTC
