### ISSUE TITLE
Bdx.matShaders.put Object disappears from view.

### ISSUE THREAD

**Issue by slightfx** [GoranM/bdx#436] opened 2015-09-12 08:21 UTC
Hi 
When I use the shader on the scene it works.
scene.filters.add(ShaderProgram.load("bdx/shaders/2d/default.vert", "bdx/shaders/2d/bloom.frag"));

But when I apply this shader to a material, the object disappears from the scene.
Bdx.matShaders.put("Material1", ShaderProgram.load("bdx/shaders/2d/default.vert", "bdx/shaders/2d/bloom.frag"));

I'm on a mac book air, so the opengl is a bit old :) could this be the problem?
Or do I need to set the material to something special?

**Comment by SolarLune** [comment] 2015-09-12 09:14
The problem is that 2D filter shader files aren't made for materials (3D objects) - that's why they're in (or will be in) different folders (shaders/2D for screen shaders, shaders/3D for material shaders), and that's why they won't work for materials. 

This is kind of an interesting problem, because running bloom probably means you want the light to bleed beyond the edges of the model, most likely, but running the shader just on the model itself wouldn't actually do that (because running a shader on the model's material would just make it run on the drawing of the model, so it wouldn't extend past the model's edges). 

It seems like the best way to do this might be to do something with offscreen rendering (draw the model you want bloomed elsewhere offscreen, in "space" with nothing else around, and then take that "screenshot" and draw it on top of the screen with the desired bloom effect). That might be something we can look into at some point.

**Comment by slightfx** [comment] 2015-09-12 09:29
Hi SolarLune 

So the example on https://github.com/GoranM/bdx/wiki/API-ShaderProgram
Is a bit off? 
Bdx.matShaders.put("PlayerMaterial", ShaderProgram.load("bdx/shaders/2d/defaultFilter.vert", "bdx/shaders/2d/defaultFilter.frag"));

Do you have a working simple shader for a Material/Object?  the 3D folder is empty.

**Comment by GoranM** [comment] 2015-09-12 17:32
> It seems like the best way to do this might be to do something with offscreen rendering (draw the model you want bloomed elsewhere offscreen, in "space" with nothing else around, and then take that "screenshot" and draw it on top of the screen with the desired bloom effect). That might be something we can look into at some point.

In the system I originally envisioned, there would be a user-defined rendering pipeline, which would implement a given material class, via shaders, offscreen-buffers, and whatever else was necessary to produce the desired visuals.

So, if you had a glowing material, there would be a rendering pipeline that would:

* Render relevant objects to offscreen buffer
* Run glow shader on that buffer (making objects "glow")
* Combine the resulting image with everything else

**Comment by SolarLune** [comment] 2015-09-13 02:38
> Hi SolarLune

So the example on https://github.com/GoranM/bdx/wiki/API-ShaderProgram
Is a bit off? 

Yeah, sorry, that was my mistake - I fixed the example to point to just an arbitrary shader (that doesn't exist) and added a note. A working test shader should be [here](https://github.com/GoranM/bdx/issues/235#issuecomment-114222337) in this thread.

> In the system I originally envisioned, there would be a user-defined rendering pipeline, which would implement a given material class, via shaders, offscreen-buffers, and whatever else was necessary to produce the desired visuals.

Hum, well, we could still do that, but it'd be pretty complex. Could you elaborate exactly what "a user-defined rendering pipeline" would mean? Like, are they like nodes (instances of a "Rendering Pass" class) that you can add to a "blank" pipeline to influence how the game is rendered ("Material > Basic Lighting > Shadowing > Bloom" kinda processing system) or what?

We could just add the ability to set the camera for a shader set to the scene.filters stack - it would automatically set the visible camera to render to that one if it's been set. We could also add an ArrayList of "relevant objects" that would render those using those filters if it's been set.

**Comment by GoranM** [comment] 2015-09-15 04:25
> Could you elaborate exactly what "a user-defined rendering pipeline" would mean?

It's essentially a function that uses shaders to render triangles with a specific material either directly to the main buffer (as usual), or to an offscreen buffer (maybe more than one) for further postprocessing (again, via shaders), and then compositing that with resulting images from other rendering pipelines, back into the main buffer.

So, it's all material based: Given a material, there's a rendering pipeline that can take its properties, and use them to generate the desired visuals.

> We could just add the ability to set the camera for a shader set to the scene.filters stack

I don't really understand what you mean by that.

**Comment by SolarLune** [comment] 2015-10-03 08:01
> I don't really understand what you mean by that.

I meant that each ShaderProgram could have a Camera reference that you can specify that it'd re-render the scene from. If it's set to null, it would just copy the main camera's render.

**Comment by GoranM** [comment] 2015-10-03 21:25
It doesn't really make sense to tie a specific camera to a specific shader. Shader programs operate on vertex and fragment data - where that data comes from is something that should be relegated to a higher-level part of the rendering system.

**Comment by SolarLune** [comment] 2015-11-01 16:41
Hey, so the recent shader improvements issue and PR will include 3D shaders with some slight improvements. They'll also be packaged in the shaders/3d directory for BDX projects, so you'll be able to modify them as necessary to improve them or add your own effects and stuff.

> So, if you had a glowing material, there would be a rendering pipeline that would:

> Render relevant objects to offscreen buffer
> Run glow shader on that buffer (making objects "glow")
> Combine the resulting image with everything else

I think I get what you mean by this now. Perhaps we can pursue this in the future at a later time once we get more progress on the engine; it sounds like a really cool and useful feature, by far.

**Comment by GoranM** [comment] 2015-11-02 04:18
I don't know ... To be honest, I don't think it can be done properly in the context of the existing libgdx rendering system.

Also, as I think I've said before, graphics are not my main focus, so I don't really have the motivation to work on that.

**Comment by SolarLune** [comment] 2015-11-02 14:15
Hmm. Well, it's something to think about - I think it's possible, we'd just have to change around how things work.

In any case, @slightfx, I think the core problem you had is solved (that using custom shaders makes objects disappear). If you build from current mainline BDX and create a new project (or just download the new shaders in the bdx/blender/bdx/gen/shaders/3d directory and use them), you should be able to use them and extend them as you wish with GLSL.

Would you mind closing this?

**Comment by SolarLune** [comment] 2015-12-07 15:56
Could someone close this? I don't think there's too much of a reason to leave this open, is there?

**Closed** 2015-12-07 18:23 UTC
