### ISSUE TITLE
Can't seem to start BDX project? (first time running)

### ISSUE THREAD

**Issue by quantumsuplex** [GoranM/bdx#1037] opened 2018-03-12 21:13 UTC
I took a screenshot of the error log for the sake of simplicity. 

Apologies in advance if I'm doing anything super obvious wrong. I'm still very new to Blender, Github as well as development in general. Prior to installing bdx I installed Java 1.8.0

https://i.imgur.com/KEBXAvB.jpg

**Comment by GoranM** [comment] 2018-03-14 05:18
Is java in your PATH?

A way to confirm this is to type `java` in a command prompt, and see if you get the expected options outline.

**Comment by rafcolson** [comment] 2018-03-19 18:27
@quantumsuplex 

Any success yet?

**Comment by rafcolson** [comment] 2018-03-29 17:12
@quantumsuplex 

If the issue is solved don't forget to close it. Thanks.

**Comment by rafcolson** [comment] 2018-04-09 16:16
After a month of non-responsiveness this issue can probably be closed.

**Closed** 2018-04-11 04:25 UTC

**Comment by quantumsuplex** [comment] 2018-04-11 04:33
Yeah I'm sorry, I kinda gave up on it. Thanks for helping out though!
